"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { coreOperatingUnits, theatreUnits, type OperatingUnit } from "@/lib/hospital-operating-model";
import { bvsPublicFacilityProfile } from "@/lib/bvs-public-facility-profile";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || "http://localhost:8000";
type Tone = "red" | "amber" | "green" | "blue";
type Dashboard = { summary?: Record<string, number>; slots?: Array<{ blocks?: any[] }> };
type Pulse = { pressure_score?: number; blocked_room_count?: number; red_conflicts?: number; amber_conflicts?: number; conflicts?: Array<{ severity?: string; department?: string; detail?: string; next_action?: string; type?: string }> };
type Row = { id: string; label: string; owner: string; source: string; status: Tone; state: string; current: string; blocker: string; route: string };

function c(t: string) { return t === "red" ? "rc-red" : t === "amber" ? "rc-amber" : t === "green" ? "rc-green" : "rc-blue"; }
function s(v: unknown) { return String(v || ""); }
function l(v: unknown) { return s(v).toLowerCase(); }
function n(v: unknown) { const x = typeof v === "number" ? v : Number(v); return Number.isFinite(x) ? x : 0; }
function tone(v: unknown): Tone { const x = l(v); return x.includes("red") || x.includes("blocked") || x.includes("high") ? "red" : x.includes("amber") || x.includes("held") || x.includes("pending") || x.includes("turnover") ? "amber" : x.includes("ready") || x.includes("active") ? "green" : "blue"; }
function sourceLabel(v: string) { return v === "public_verified" ? "public verified" : "configurable"; }

async function getJson<T>(path: string): Promise<T | null> { try { const res = await fetch(`${API_BASE}${path}`, { cache: "no-store" }); return res.ok ? await res.json() : null; } catch { return null; } }
function blocks(data: Dashboard | null) { return (data?.slots || []).flatMap((slot) => slot.blocks || []); }
function findBlock(unit: OperatingUnit, data: Dashboard | null) { return blocks(data).find((b) => `${l(b?.room?.name)} ${l(b?.room?.department)} ${l(b?.block_type)}`.includes(l(unit.label.split(" ")[0]))) || null; }
function conflicts(unit: OperatingUnit, pulse: Pulse | null) { return (pulse?.conflicts || []).filter((x) => `${l(x.department)} ${l(x.detail)} ${l(x.type)}`.includes(l(unit.label.split(" ")[0]))); }
const fallback = ["Blocked", "Active", "Turnover", "Ready", "Held", "Active", "Ready", "Consent", "Staff gap", "Emergency", "Kit held"];

function row(unit: OperatingUnit, data: Dashboard | null, pulse: Pulse | null, index: number): Row {
  const b = findBlock(unit, data); const hits = conflicts(unit, pulse); const hard = n(b?.pressure?.hard_blocks?.length); const warn = n(b?.pressure?.warnings?.length) + hits.length;
  return { id: unit.id, label: unit.label, owner: unit.ownerRole, source: unit.source, status: hard ? "red" : warn ? "amber" : tone(b?.status || (unit.type === "theatre" ? fallback[index % fallback.length] : "monitored")), state: s(b?.status || (unit.type === "theatre" ? fallback[index % fallback.length] : "monitored")), current: s(b?.episode?.episode_ref || b?.episode?.patient?.name || "—"), blocker: s(b?.next_action?.detail || hits[0]?.next_action || hits[0]?.detail || unit.blockers[0]), route: unit.route };
}

function Kpis({ dashboard, pulse }: { dashboard: Dashboard | null; pulse: Pulse | null }) {
  const summary = dashboard?.summary || {}; const pressure = n(pulse?.pressure_score) || Math.min(100, n(pulse?.red_conflicts || summary.red_slots) * 15 + n(pulse?.amber_conflicts || summary.amber_slots) * 6);
  const cards = [["Pressure", `${pressure}/100`, pressure >= 70 ? "red" : pressure >= 35 ? "amber" : "green"], ["Public theatres", String(bvsPublicFacilityProfile.publicVerifiedOperatingTheatres), "blue"], ["Interventional", String(bvsPublicFacilityProfile.publicVerifiedInterventionalSuites), "blue"], ["Config spaces", String(theatreUnits.length), "amber"], ["Blocked rooms", String(n(pulse?.blocked_room_count)), n(pulse?.blocked_room_count) ? "amber" : "green"], ["Schedule", String(n(summary.schedule_blocks)), "blue"]] as const;
  return <div className="rc-kpis">{cards.map(([label, value, status]) => <div className={`rc-kpi ${c(status)}`} key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>;
}

function Table({ rows }: { rows: Row[] }) { return <div className="rc-table"><div className="rc-tr rc-th"><span>Unit</span><span>State</span><span>Current</span><span>Owner</span><span>Blocker</span></div>{rows.map((r) => <Link href={r.route} className={`rc-tr ${c(r.status)}`} key={r.id}><span><b>{r.label}</b><small>{sourceLabel(r.source)}</small></span><span>{r.state}</span><span>{r.current}</span><span>{r.owner}</span><span>{r.blocker}</span></Link>)}</div>; }
function Grid({ rows }: { rows: Row[] }) { return <div className="rc-theatre-grid">{rows.map((r) => <Link href={r.route} className={`rc-theatre ${c(r.status)}`} key={r.id}><b>{r.label}</b><strong>{r.state}</strong><span>{r.current}</span><small>{sourceLabel(r.source)} · {r.blocker}</small></Link>)}</div>; }
function Section({ label, title, children }: { label: string; title: string; children: React.ReactNode }) { return <section className="rc-panel"><div className="rc-head"><span>{label}</span><h2>{title}</h2></div>{children}</section>; }

export function ResourceControlBoard() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [pulse, setPulse] = useState<Pulse | null>(null); const [updated, setUpdated] = useState("fallback mode");
  useEffect(() => { let mounted = true; async function load() { const [dash, live] = await Promise.all([getJson<Dashboard>("/api/dashboard/intelligence"), getJson<Pulse>("/api/conflict-engine/pulse")]); if (!mounted) return; setDashboard(dash); setPulse(live); setUpdated(dash || live ? new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "fallback mode"); } load(); const timer = window.setInterval(load, 30000); return () => { mounted = false; window.clearInterval(timer); }; }, []);
  const theatres = theatreUnits.map((unit, i) => row(unit, dashboard, pulse, i)); const support = coreOperatingUnits.filter((unit) => !unit.id.startsWith("theatre-")).map((unit, i) => row(unit, dashboard, pulse, i));
  const diagnostics = support.filter((r) => ["mri", "ct", "xray", "ultrasound", "radiotherapy", "lab", "interventional-suite-1"].includes(r.id)); const beds = support.filter((r) => ["icu", "recovery", "ward"].includes(r.id)); const admin = support.filter((r) => ["pharmacy", "insurance", "owner-comms", "stock-equipment", "governance"].includes(r.id));
  return <div className="rc-board"><style>{css}</style><header className="rc-hero"><div><span>BVS public profile + configurable resources · {updated}</span><h1>Resource control</h1><p>Verified public model: {bvsPublicFacilityProfile.publicVerifiedOperatingTheatres} operating theatres, {bvsPublicFacilityProfile.publicVerifiedInterventionalSuites} interventional suite, MRI, CT, ultrasound, radiography/fluoroscopy and radiotherapy. Internal theatre-like capacity remains configurable.</p></div><nav><Link href="/hospital-board">Daily board</Link><Link href="/interrupts">Pulse</Link><Link href="/actions">Actions</Link></nav></header><Kpis dashboard={dashboard} pulse={pulse} /><div className="rc-layout"><main><Section label="operating complex" title="Public verified theatres plus configurable theatre-like spaces"><Grid rows={theatres} /></Section><Section label="all resources" title="Operating units by blocker and owner"><Table rows={[...theatres, ...support]} /></Section></main><aside><Section label="diagnostics + treatment" title="MRI / CT / X-ray / ultrasound / IR / radiotherapy / lab"><Table rows={diagnostics} /></Section><Section label="beds" title="ICU / recovery / ward"><Table rows={beds} /></Section><Section label="admin + support" title="Pharmacy / insurance / comms / stock"><Table rows={admin} /></Section></aside></div></div>;
}

const css = `.rc-board{min-height:100vh;background:#050b14;color:#e6edf7;padding:20px;font-family:Inter,system-ui,sans-serif}.rc-hero{display:flex;justify-content:space-between;gap:18px;border:1px solid #274568;border-radius:24px;padding:22px;background:linear-gradient(135deg,#0c182a,#07111f)}.rc-hero span,.rc-head span{color:#5eead4;text-transform:uppercase;letter-spacing:.13em;font-weight:900;font-size:12px}.rc-hero h1{font-size:clamp(36px,5vw,64px);line-height:.95;margin:8px 0}.rc-hero p{max-width:900px;color:#a7b5c8}.rc-hero nav{display:flex;gap:8px;flex-wrap:wrap;align-content:flex-start}.rc-hero a,.rc-tr,.rc-theatre{color:#e6edf7;text-decoration:none}.rc-hero a{border:1px solid #31557f;background:#10223c;border-radius:999px;padding:9px 12px;font-weight:800}.rc-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:14px 0}.rc-kpi,.rc-panel{background:#0b1728;border:1px solid #243b60;border-radius:18px;padding:13px}.rc-kpi span{display:block;color:#9fb0c6;text-transform:uppercase;font-size:11px}.rc-kpi strong{font-size:24px}.rc-layout{display:grid;grid-template-columns:minmax(0,1fr) 440px;gap:14px}.rc-layout main,aside{display:grid;gap:14px;align-content:start}.rc-head{display:flex;justify-content:space-between;border-bottom:1px solid #243b60;margin-bottom:12px;padding-bottom:10px}.rc-head h2{margin:0;font-size:19px}.rc-red{border-color:#ef4444!important;background:#2a0d16!important}.rc-amber{border-color:#f59e0b!important;background:#2a1a08!important}.rc-green{border-color:#22c55e!important;background:#071d13!important}.rc-blue{border-color:#38bdf8!important;background:#071a2a!important}.rc-theatre-grid{display:grid;grid-template-columns:repeat(11,minmax(120px,1fr));gap:8px;overflow:auto}.rc-theatre{display:grid;gap:5px;border:1px solid #28466e;border-radius:14px;background:#101d31;padding:10px}.rc-theatre strong{font-size:18px}.rc-theatre small,.rc-theatre span,.rc-tr small{display:block;color:#a7b5c8}.rc-table{display:grid;gap:4px;overflow:auto}.rc-tr{display:grid;grid-template-columns:1fr .8fr .85fr .9fr 1.4fr;gap:8px;border:1px solid #28466e;border-radius:12px;background:#091321;padding:9px;min-width:720px}.rc-th{background:#10223c;color:#93c5fd;font-size:12px;text-transform:uppercase;font-weight:900}.rc-tr span{overflow:hidden;text-overflow:ellipsis}.rc-tr:not(.rc-th):hover,.rc-theatre:hover{outline:2px solid #5eead4}@media(max-width:1250px){.rc-layout{grid-template-columns:1fr}.rc-kpis{grid-template-columns:repeat(3,1fr)}.rc-theatre-grid{grid-template-columns:repeat(11,130px)}}@media(max-width:720px){.rc-board{padding:10px}.rc-hero{flex-direction:column}.rc-kpis{grid-template-columns:1fr}}`;
